export const MOVE_REQUEST = 'MOVE_REQUEST';
export const MOVE_REQUEST_SUCCESS = 'MOVE_REQUEST_SUCCESS';

export const CONNECT_MQTT = 'CONNECT_MQTT';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const UPDATE_PROGRESS_COMPLETED = 'UPDATE_PROGRESS_COMPLETED';